apiVersion: v1
kind: Service
metadata:
  name: {{ include "porter-galaxy.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "porter-galaxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "porter-galaxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
