apiVersion: v2
name: porter-galaxy
description: Galaxy-style Kubernetes cluster graph visualizer
type: application
version: 0.17.0
appVersion: "0.17.0"
keywords:
  - kubernetes
  - visualization
  - cluster
  - topology
home: https://github.com/noeosorio/porter-galaxy
icon: https://raw.githubusercontent.com/NoeOsorio/porter-galaxy/main/frontend/public/black-hole.png
sources:
  - https://github.com/noeosorio/porter-galaxy
maintainers:
  - name: noeosorio
    email: noe@porter.run
